### ISSUE TITLE
ModuleNotFoundError: No module named 'imread_from_url'

### ISSUE THREAD

**Issue by gouravAtre** [ibaiGorordo/ONNX-YOLOv8-Instance-Segmentation#1]
I'm getting "ModuleNotFoundError: No module named 'imread_from_url' " while running "image_instance_segmentation.py".
Please update the repo with this required module.

**Comment by ibaiGorordo** [comment]
Please follow the instructions:
https://github.com/ibaiGorordo/ONNX-YOLOv8-Instance-Segmentation#installation

https://github.com/ibaiGorordo/ONNX-YOLOv8-Instance-Segmentation/blob/01d95efb4d1974497646b675080a7dd2999459ff/requirements.txt#L2

**Comment by gouravAtre** [comment]
My bad. Got it. Thank you @ibaiGorordo
